version: '3'
services:
  timeoffapp:
    image: "timeoff-management-application" #+":$BUILD_NUMBER"  
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
       - "TZ=America/Bogota"
