version: '3'
services:
  timeoffapp:
    image: "192.168.86.86:8081/timeoff-management-application" #+":$BUILD_NUMBER"  
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3333:3000"
    environment:
       - "TZ=America/Bogota"
