version: '3'
services:
  timeoffapp:
    image: "timeoff-management-application" #+":$BUILD_NUMBER"  
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
       - "TZ=America/Bogota"
    mem_limit: 10000
